# Generated by MCP Diagnosis Tool: server-side template (v 1.2.1.15)
spec = {
  "mode": "stdio",
  "command": "npx",
  "args": [
    "-y",
    "@playwright/mcp@latest",
    "--config",
    "C:/Users/jenss/ONEDRI~2/Code/Test/mcpconfig/subconfigs/plwghtconfig_cognitive.json"
  ]
}
steps = []
def run():
    print('No steps defined. Spec:', spec)
if __name__ == '__main__':
    run()
