# Generated by MCP Diagnosis Tool: server-side template (v 1.2.1.15)
spec = {
  "mode": "http",
  "url": "http://localhost:3060"
}
steps = []
def run():
    print('No steps defined. Spec:', spec)
if __name__ == '__main__':
    run()
