/*
 * server.js
 *
 * This file starts a small Express server that exposes a single API endpoint
 * for diagnosing MCP servers and serves a static front‑end for interacting
 * with the diagnostic logic. The API delegates the heavy lifting to the
 * mcpDoctor module which uses the MCP client SDK to negotiate the
 * initialize/initialized handshake and list available tools/prompts/resources.
 */

const express = require('express');
const cors = require('cors');
const path = require('path');
const JSZip = require('jszip');
const { log, logError, logWithTruncation, LOG_PATH, getRecent, attachConsoleInterceptors, detachConsoleFile, rotateConsoleFile, startRolling24Hours, getNextRotationTs } = require('./logger');
const fs = require('fs');
const { spawn } = require('child_process');

// Debug signature to verify correct file is running and to force-create debug log file
try {
  console.log('[DEBUG_SIGNATURE] server.js loaded (enhanced logging)');
  fs.appendFileSync(LOG_PATH, '', { encoding: 'utf8' });
} catch (_) {}

const {
  diagnose,
  parseMcpConfigContent,
  diagnoseConfigEntries,
  mergeNormalizedConfig,
  removeServerFromConfig,
  serializeMcpConfigToJson,
  serializeMcpConfigToToml,
  serializeServerSnippet,
  callTool,
  listSessions,
  closeSession,
  closeAllSessions,
  openSessionForSpec,
  restartSessionForSpec,
  renderToolReportMarkdown
} = require('./mcpDoctor');

// Small helper to create simple export artifacts on the server side so clients
// (or automated tests) can validate export logic without relying on the browser
// File format mirrors what the client exports: YAML, JS, PY and a baseName
function buildExportTemplate({ spec = {}, serverName = 'server', appVersion = 'dev' } = {}) {
  const displayName = serverName || (spec?.url || spec?.command || 'server');
  const baseName = `${displayName.replace(/[^a-zA-Z0-9_-]/g, '_')}_${new Date().toISOString().replace(/[:.]/g, '-')}_session`;

  const snippetCommentYaml = `# Exported with MCP Diagnosis Tool v ${appVersion}\n`;
  const workflow = {
    version: 1,
    exported_at: new Date().toISOString(),
    server: { name: displayName, spec },
    steps: []
  };

  // simple YAML using single quoted style (reuse client logic lightly)
  function yamlScalar(v) {
    if (v === null || v === undefined) return 'null';
    if (typeof v === 'string') return `'${String(v).replace(/'/g, "''")}'`;
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    return String(v);
  }
  function toSingleQuotedYAML(obj, indent = 0) {
    const pad = '  '.repeat(indent);
    if (Array.isArray(obj)) {
      if (obj.length === 0) return pad + '[]';
      return obj.map(i => `${pad}- ${typeof i === 'object' ? '\n' + toSingleQuotedYAML(i, indent + 1) : yamlScalar(i)}`).join('\n');
    }
    if (obj && typeof obj === 'object') {
      const keys = Object.keys(obj);
      if (!keys.length) return pad + '{}';
      return keys.map(k => {
        const v = obj[k];
        const key = /^[A-Za-z0-9_]+$/.test(k) ? k : `'${String(k).replace(/'/g, "''")}'`;
        if (v && typeof v === 'object') return `${pad}${key}:\n${toSingleQuotedYAML(v, indent + 1)}`;
        return `${pad}${key}: ${yamlScalar(v)}`;
      }).join('\n');
    }
    return pad + yamlScalar(obj);
  }

  const yaml = snippetCommentYaml + toSingleQuotedYAML(workflow) + '\n';

  const js = `/* Generated by MCP Diagnosis Tool: server-side template (v ${appVersion}) */\n` +
    `const spec = ${JSON.stringify(spec, null, 2)};\n` +
    `// Steps are empty in template\n` +
    `const steps = [];\n` +
    `async function run(){ console.log('No steps defined. Spec:', spec); }\n` +
    `module.exports = { spec, steps, run };\n`;

  const py = `# Generated by MCP Diagnosis Tool: server-side template (v ${appVersion})\n` +
    `spec = ${JSON.stringify(spec, null, 2)}\n` +
    `steps = []\n` +
    `def run():\n` +
    `    print('No steps defined. Spec:', spec)\n` +
    `if __name__ == '__main__':\n` +
    `    run()\n`;

  // Build API-oriented export artifacts that call the MCP Diagnosis HTTP API
  // These scripts do NOT launch MCP servers directly; they call the diagnosis
  // server endpoints to open sessions and replay calls.
  const apiYaml = `# API replay manifest for MCP Diagnosis Tool v ${appVersion}\n` +
    `# Contains high-level steps to reproduce a session via the diagnosis server API\n` +
    `server: ${displayName}\n` +
    `spec: ${JSON.stringify(spec, null, 2)}\n` +
    `steps: []\n`;

  const apiJs = `// API replay script for MCP Diagnosis Tool v ${appVersion}\n` +
    `// This script calls the local MCP Diagnosis HTTP API to open a session and run tools.\n` +
    `// Usage: node ${baseName}.api.js --server http://localhost:3060\n` +
    `const fetch = require('node-fetch');\n` +
    `(async function(){\n` +
    `  const base = process.argv[2] || 'http://localhost:3060';\n` +
    `  const spec = ${JSON.stringify(spec, null, 2)};\n` +
    `  console.log('Opening session for spec', spec);\n` +
    `  const open = await fetch(base + '/api/sessions/open', { method: 'POST', headers: { 'Content-Type':'application/json' }, body: JSON.stringify({ spec }) });\n` +
    `  const o = await open.json();\n` +
    `  if (!o || !o.sessionId) { console.error('Failed to open session', o); process.exit(2); }\n` +
    `  const sessionId = o.sessionId;\n` +
    `  console.log('Session opened', sessionId);\n` +
    `  // No steps defined in template. Replace with calls to POST /api/tools/call if needed.\n` +
    `  // Example: await fetch(base + '/api/tools/call', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ sessionId, tool: 'toolName', args: {} }) });\n` +
    `  // Close the session when done\n` +
    `  await fetch(base + '/api/sessions/close', { method: 'POST', headers: { 'Content-Type':'application/json' }, body: JSON.stringify({ sessionId }) });\n` +
    `  console.log('Session closed');\n` +
    `})();\n`;

  const apiPs = `# API replay PowerShell script for MCP Diagnosis Tool v ${appVersion}\n` +
    `# Usage: powershell -File ${baseName}.api.ps1 -BaseUrl http://localhost:3060\n` +
    `$BaseUrl = $args[0] ; if (-not $BaseUrl) { $BaseUrl = 'http://localhost:3060' }\n` +
    `$spec = ${JSON.stringify(spec, null, 2)}\n` +
    `Write-Host "Opening session for spec via $BaseUrl"\n` +
    `$resp = Invoke-RestMethod -Method Post -Uri ($BaseUrl + '/api/sessions/open') -ContentType 'application/json' -Body (ConvertTo-Json @{ spec = $spec } -Depth 10)\n` +
    `if (-not $resp.sessionId) { Write-Error "Failed to open session: $($resp | ConvertTo-Json -Depth 5)" ; exit 2 }\n` +
    `$sessionId = $resp.sessionId\n` +
    `Write-Host "Session opened: $sessionId"\n` +
    `# No steps defined in template. Use Invoke-RestMethod -Uri ($BaseUrl + '/api/tools/call') -Method Post -ContentType 'application/json' -Body (ConvertTo-Json @{ sessionId = $sessionId; tool='toolName'; args=@{} } -Depth 10)\n` +
    `Write-Host "Closing session"\n` +
    `Invoke-RestMethod -Method Post -Uri ($BaseUrl + '/api/sessions/close') -ContentType 'application/json' -Body (ConvertTo-Json @{ sessionId = $sessionId } -Depth 5)\n`;

  return { yaml, js, py, apiYaml, apiJs, apiPs, baseName };
}

// Server control state for UI and log release attempts
const SERVER_LOG_PATH = path.join(__dirname, 'server.log');
let LOG_DETACHED = false;
const SERVER_START_TIME = Date.now(); // Timestamp when server started

const app = express();
const PORT = process.env.PORT || 3060;

// Application version (read from package.json when available)
try {
  const pkg = require('./package.json');
  process.env.APP_VERSION = process.env.APP_VERSION || (pkg && pkg.version) || 'dev';
} catch (_) {
  process.env.APP_VERSION = process.env.APP_VERSION || 'dev';
}

// Enable JSON body parsing (increase limit to handle large workflow manifests)
app.use(express.json({ limit: '10mb' }));
// Allow cross‑origin requests in case the UI is served from a different host
app.use(cors());
// Attach console/stdout/stderr to managed server.log stream (allows rotate/detach)
try { attachConsoleInterceptors(); log('raw_log_attach', { path: path.join(__dirname, 'server.log') }); } catch(_) {}

// Start 24h rolling rotation (daily at local midnight)
try { startRolling24Hours(); log('raw_log_roll_schedule', {}); } catch(_) {}


// Startup log
log('server_start', { port: Number(process.env.PORT || 3060), logPath: LOG_PATH });

// Request logger middleware (method, url, basic body keys)
app.use((req, _res, next) => {
  try {
    const keys = req.body && typeof req.body === 'object' ? Object.keys(req.body) : [];
    log('http_request', { method: req.method, url: req.originalUrl || req.url, bodyKeys: keys });
  } catch (_) {
    /* ignore */
  }
  next();
});

// API route for diagnosing servers
app.post('/api/diagnose', async (req, res) => {
  const { mode, url, command, args } = req.body || {};
  log('api_diagnose_request', { mode, url, command, args });
  if (!mode) {
    return res.status(400).json({ error: 'mode is required ("http" or "stdio")' });
  }
  try {
    const spec = { mode };
    if (mode === 'http') {
      spec.url = url;
    } else if (mode === 'stdio') {
      spec.command = command;
      spec.args = Array.isArray(args) ? args : typeof args === 'string' ? args.split(/\s+/) : [];
    }
    const result = await diagnose(spec);
    log('api_diagnose_response', { ok: result?.ok, transport: result?.transport });
    res.json(result);
  } catch (err) {
    logError('api_diagnose_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for diagnosing all servers within an uploaded MCP config
app.post('/api/config/diagnose', async (req, res) => {
  const { configText, config, configFormat } = req.body || {};
  if (!configText && !config) {
    return res.status(400).json({ error: 'configText (string) or config (object) is required' });
  }
  try {
    const normalized = parseMcpConfigContent(configText ?? config, configFormat);
    const results = await diagnoseConfigEntries(normalized);
    const servers = attachConfigMetadata(normalized, results);
    res.json({ ok: true, format: normalized.format, config: normalized, servers });
  } catch (err) {
    const status = err.code && err.code.startsWith('CONFIG_') ? 400 : 500;
    // Log full stack for debugging (temporary)
    try { logError('config_diagnose_error', err); } catch (_) {}
    try { log('config_diagnose_stack', { stack: err && err.stack ? String(err.stack).slice(0,2000) : String(err) }); } catch (_) {}
    // Return sanitized message to client (do not leak internal stacks)
    const responseError = { kind: 'config_error', details: 'Internal config processing error (see server logs)' };
    res.status(status).json({ ok: false, error: responseError });
  }
});

// API route for converting/saving configs
app.post('/api/config/export', async (req, res) => {
  const { config, targetFormat } = req.body || {};
  if (!config || typeof config !== 'object' || !targetFormat) {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'config and targetFormat are required' } });
  }
  try {
    let content;
    if (targetFormat === 'json') {
      content = serializeMcpConfigToJson(config);
    } else if (targetFormat === 'toml') {
      content = serializeMcpConfigToToml(config);
    } else {
      return res.status(400).json({ ok: false, error: { kind: 'unsupported_format', details: 'targetFormat must be "json" or "toml"' } });
    }
    res.json({ ok: true, format: targetFormat, content });
  } catch (err) {
    const status = err.code && err.code.startsWith('CONFIG_') ? 400 : 500;
    res.status(status).json({ ok: false, error: { kind: 'config_export_error', details: err.message } });
  }
});

// Simple Playwright codegen controller endpoints
const activeCodegen = new Map();

app.post('/api/playwright/codegen/start', (req, res) => {
  try {
    const { url, mode } = req.body || {};
    if (!url || typeof url !== 'string') return res.status(400).json({ ok: false, error: { details: 'url (string) is required' } });
    const id = `pg-${Date.now()}`;
    const outDir = path.join(__dirname, 'playwright-recordings');
    try { fs.mkdirSync(outDir, { recursive: true }); } catch (_) {}
    const outPath = path.join(outDir, `${id}.playwright.js`);

    if (mode === 'visible') {
      // Use Playwright CLI 'codegen' for an interactive visible recorder that
      // shows the codegen UI. This will open a browser window and allow the
      // user to interact with the page; the CLI will write the script to outPath
      // when the process exits.
      // Prefer local playwright binary from node_modules/.bin when available
      let localBin = null;
      try {
        if (process.platform === 'win32') localBin = path.join(__dirname, 'node_modules', '.bin', 'playwright.cmd');
        else localBin = path.join(__dirname, 'node_modules', '.bin', 'playwright');
        if (!fs.existsSync(localBin)) localBin = null;
      } catch (_) { localBin = null; }

      let execCmd;
      let execArgs;
      if (localBin) {
        // On Windows the '.cmd' wrapper should be invoked via cmd.exe to ensure
        // arguments are passed correctly. On POSIX we can call the binary directly.
        if (process.platform === 'win32' && localBin.toLowerCase().endsWith('.cmd')) {
          execCmd = 'cmd.exe';
          // Quote paths so cmd.exe handles spaces correctly (Windows uses cmd wrappers)
          const quotedBin = '"' + localBin + '"';
          const quotedOut = '"' + outPath + '"';
          execArgs = ['/c', quotedBin, 'codegen', url, '--output', quotedOut];
        } else {
          execCmd = localBin;
          execArgs = ['codegen', url, '--output', outPath];
        }
      } else {
        // Fallback to npx invoking playwright codegen
        execCmd = 'npx';
        execArgs = ['playwright', 'codegen', url, '--output', outPath];
      }

      try {
        log('playwright_codegen_spawn', { id, execCmd, execArgs: Array.isArray(execArgs) ? execArgs.slice(0,8) : execArgs });
      } catch (_) {}

      // Prepare spawn options
      const spawnOptions = { stdio: ['ignore', 'pipe', 'pipe'], detached: false, shell: false, cwd: path.join(__dirname) };
      let proc;
      // On Windows, calling the .cmd wrapper via a single shell string is more reliable
      // when paths contain spaces. Use shell execution for the Windows case only.
      if (process.platform === 'win32' && localBin && localBin.toLowerCase().endsWith('.cmd')) {
        const cmdString = `"${localBin}" codegen "${url}" --output "${outPath}"`;
        proc = spawn(cmdString, { ...spawnOptions, shell: true });
      } else {
        proc = spawn(execCmd, execArgs, spawnOptions);
      }
      activeCodegen.set(id, { proc, outPath, startedAt: Date.now(), mode: 'visible' });
      proc.stdout && proc.stdout.on('data', (d) => { try { log('playwright_recorder_stdout', { mode: 'visible', id, line: String(d).slice(0,200) }); } catch(_){} });
      proc.stderr && proc.stderr.on('data', (d) => { try { log('playwright_recorder_stderr', { mode: 'visible', id, line: String(d).slice(0,1000) }); } catch(_){} });
      proc.on('exit', (code, sig) => {
        try { log('playwright_recorder_exit', { mode: 'visible', id, code, sig, outPath }); } catch(_) {}
      });
      res.json({ ok: true, sessionId: id, outPath });
      return;
    }

    if (mode === 'auto') {
      // Spawn the automatic helper for programmatic runs
      const helper = path.join(__dirname, 'scripts', 'playwright_auto_recorder.js');
      const proc = spawn(process.execPath, [helper, '--url', url, '--out', outPath], { 
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: false,
        shell: false,
        cwd: path.join(__dirname, 'scripts')
      });
      activeCodegen.set(id, { proc, outPath, startedAt: Date.now(), mode: 'auto' });
      proc.stdout && proc.stdout.on('data', (d) => { try { log('playwright_recorder_stdout', { mode: 'auto', id, line: String(d).slice(0,200) }); } catch(_){} });
      proc.stderr && proc.stderr.on('data', (d) => { try { log('playwright_recorder_stderr', { mode: 'auto', id, line: String(d).slice(0,1000) }); } catch(_){} });
      proc.on('exit', (code, sig) => {
        try { log('playwright_recorder_exit', { mode: 'auto', id, code, sig, outPath }); } catch(_) {}
      });
      res.json({ ok: true, sessionId: id, outPath });
      return;
    }

    // Legacy: spawn Playwright CLI in codegen mode via npx. This assumes 'npx playwright codegen' is available.
    const args = ['playwright', 'codegen', url, '--output', outPath];
    const proc = spawn('npx', args, { stdio: 'ignore', detached: false });
    activeCodegen.set(id, { proc, outPath, startedAt: Date.now(), mode: 'codegen' });
    proc.on('exit', (code, sig) => {
      try { log('playwright_codegen_exit', { id, code, sig, outPath }); } catch(_) {}
    });
    res.json({ ok: true, sessionId: id, outPath });
  } catch (err) {
    logError('playwright_codegen_start_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

app.post('/api/playwright/codegen/stop', async (req, res) => {
  try {
    const { sessionId } = req.body || {};
    if (!sessionId) return res.status(400).json({ ok: false, error: { details: 'sessionId is required' } });
    const info = activeCodegen.get(sessionId);
    if (!info) return res.status(404).json({ ok: false, error: { details: 'session not found' } });
    try {
      // Ask the process to exit gracefully first
      try { info.proc.kill(); } catch (_) {}
    } catch (e) {
      // ignore
    }

    // Wait for the recorder to write the output file. Some recorder helpers
    // are interactive and flush the file on graceful exit; give them a short
    // window to finish. Poll the file for up to 5s.
    let content = '';
    const maxWait = 5000;
    const start = Date.now();
    while (Date.now() - start < maxWait) {
      try {
        if (fs.existsSync(info.outPath)) {
          const st = fs.statSync(info.outPath);
          if (st.size && st.size > 0) {
            content = fs.readFileSync(info.outPath, { encoding: 'utf8' });
            break;
          }
        }
      } catch (e) {
        // log and continue polling
        try { log('playwright_stop_poll_error', { id: sessionId, err: String(e).slice(0,200) }); } catch(_){}
      }
      // Give process some time to flush
      await new Promise((r) => setTimeout(r, 200));
    }
    // If still empty, attempt one final read (may be empty) and proceed
    try {
      if (!content && fs.existsSync(info.outPath)) {
        content = fs.readFileSync(info.outPath, { encoding: 'utf8' });
      }
    } catch (e) {
      logError('playwright_read_error', e);
    }
    activeCodegen.delete(sessionId);
    res.json({ ok: true, sessionId, outPath: info.outPath, content });
  } catch (err) {
    logError('playwright_codegen_stop_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Status endpoint for a codegen session. Returns whether the session is active
app.get('/api/playwright/codegen/status', (req, res) => {
  try {
    const sessionId = req.query.sessionId || req.body && req.body.sessionId;
    if (!sessionId) return res.status(400).json({ ok: false, error: { details: 'sessionId query parameter is required' } });
    const info = activeCodegen.get(String(sessionId));
    if (!info) return res.json({ ok: true, sessionId, running: false });
    // Try to check process alive state
    let running = true;
    try {
      const pid = info.proc && info.proc.pid;
      if (!pid) running = true; // unknown, assume running
      else {
        // On Node.js, process.kill(pid, 0) throws if not running
        try { process.kill(pid, 0); running = true; } catch (e) { running = false; }
      }
    } catch (e) {
      running = true;
    }
    return res.json({ ok: true, sessionId, running: !!running, mode: info.mode, outPath: info.outPath });
  } catch (err) {
    logError('playwright_codegen_status_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// API route for merging a single server config into the current config
app.post('/api/config/add-server', async (req, res) => {
  const { baseConfig, additionText, additionFormat } = req.body || {};
  if (!additionText || typeof additionText !== 'string') {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'additionText (string) is required' } });
  }
  try {
    const addition = parseMcpConfigContent(additionText, additionFormat);
    if (!addition.servers.length) {
      const error = new Error('Provided config did not contain any MCP servers.');
      error.code = 'CONFIG_SCHEMA_ERROR';
      throw error;
    }
    let baseNormalized = null;
    if (baseConfig && typeof baseConfig === 'object') {
      baseNormalized = JSON.parse(JSON.stringify(baseConfig));
      if (!Array.isArray(baseNormalized.servers)) {
        baseNormalized.servers = [];
      }
      if (!baseNormalized.topLevel || typeof baseNormalized.topLevel !== 'object') {
        baseNormalized.topLevel = {};
      }
      if (!baseNormalized.format) {
        baseNormalized.format = addition.format ?? 'json';
      }
    }
    const merged = mergeNormalizedConfig(baseNormalized, addition);
    const results = await diagnoseConfigEntries(merged);
    const servers = attachConfigMetadata(merged, results);
    res.json({ ok: true, config: merged, servers });
  } catch (err) {
    const status = err.code && err.code.startsWith('CONFIG_') ? 400 : 500;
    res.status(status).json({ ok: false, error: { kind: 'config_merge_error', details: err.message } });
  }
});

// Server-side export template for testing exporter logic without browser
app.post('/api/export/template', (req, res) => {
  try {
    const { spec, serverName, appVersion } = req.body || {};
    const version = process.env.APP_VERSION || appVersion || 'server';
    const artifacts = buildExportTemplate({ spec: spec || {}, serverName: serverName || (spec && (spec.url || spec.command)) || 'server', appVersion: version });
    res.json({ ok: true, ...artifacts });
  } catch (err) {
    logError('export_template_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Serialize a server object into a config snippet (JSON or TOML)
app.post('/api/export/serialize-snippet', (req, res) => {
  try {
    const { server, format } = req.body || {};
    if (!server || typeof server !== 'object') return res.status(400).json({ ok: false, error: { details: 'server (object) is required' } });
    const snippet = serializeServerSnippet(server, format === 'toml' ? 'toml' : 'json');
    res.json({ ok: true, snippet });
  } catch (err) {
    logError('serialize_snippet_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Parse an arbitrary snippet (JSON or TOML) and return the parsed normalized object.
app.post('/api/export/parse-snippet', (req, res) => {
  try {
    const { text } = req.body || {};
    if (!text || typeof text !== 'string') return res.status(400).json({ ok: false, error: { details: 'text (string) is required' } });
    try {
      const parsed = parseMcpConfigContent(text);
      // Return the normalized parse result (format, servers, topLevel)
      return res.json({ ok: true, parsed });
    } catch (err) {
      return res.status(400).json({ ok: false, error: { details: err.message } });
    }
  } catch (err) {
    logError('parse_snippet_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Build an export directly from a raw snippet (server-side helper for tests)
app.post('/api/export/from-snippet', (req, res) => {
  try {
    const { snippet, serverName, appVersion } = req.body || {};
    if (!snippet || typeof snippet !== 'string') return res.status(400).json({ ok: false, error: { details: 'snippet (string) is required' } });
    // Try parsing
    let parsed;
    try {
      parsed = parseMcpConfigContent(snippet);
    } catch (err) {
      return res.status(400).json({ ok: false, error: { details: `parse failed: ${err.message}` } });
    }

    // Attempt to extract a server spec
    let specObj = null;
    if (parsed && typeof parsed === 'object') {
      if (Array.isArray(parsed.servers) && parsed.servers.length) {
        specObj = parsed.servers[0];
      } else if (parsed.mcpServers && typeof parsed.mcpServers === 'object') {
        // pick by serverName or first
        if (serverName && parsed.mcpServers[serverName]) specObj = parsed.mcpServers[serverName];
        else {
          const keys = Object.keys(parsed.mcpServers);
          if (keys.length) specObj = parsed.mcpServers[keys[0]];
        }
      }
      // If parsed itself looks like a server spec
      if (!specObj && (parsed.mode || parsed.command || parsed.url || parsed.args)) {
        specObj = parsed;
      }
    }

    if (!specObj) return res.status(400).json({ ok: false, error: { details: 'No server spec found in snippet' } });

    const artifacts = buildExportTemplate({ spec: specObj, serverName: serverName || specObj.name || 'server', appVersion: appVersion || process.env.APP_VERSION || 'dev' });
    return res.json({ ok: true, ...artifacts, parsed });
  } catch (err) {
    logError('export_from_snippet_error', err);
    res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Save exported workflow artifacts into a server-side folder with proper subdirectories
// Body: { baseName: string, targets: [{ name: 'MCPflow/..'|'APIflow/..'|'json/..', content: string, mime?: string }] }
// Returns: { ok: true, folder: relativePath, absoluteFolder: string, files: string[] }
app.post('/api/export/save', (req, res) => {
  try {
    const { baseName, targets } = req.body || {};
    if (!baseName || !Array.isArray(targets) || !targets.length) {
      return res.status(400).json({ ok: false, error: { details: 'baseName and targets array are required' } });
    }
    const rootDir = path.join(__dirname, 'imports', 'exports', String(baseName));
    try { fs.mkdirSync(rootDir, { recursive: true }); } catch (_) {}
    const written = [];
    for (const t of targets) {
      if (!t || typeof t.name !== 'string' || typeof t.content !== 'string') continue;
      // Normalize and ensure path stays within rootDir
      const safeName = t.name.replace(/\\/g, '/');
      if (safeName.includes('..')) {
        return res.status(400).json({ ok: false, error: { details: 'Invalid file path' } });
      }
      const absPath = path.join(rootDir, safeName);
      const dir = path.dirname(absPath);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(absPath, t.content, { encoding: 'utf8' });
      written.push(absPath);
    }
    return res.json({ ok: true, folder: path.join('imports', 'exports', String(baseName)), absoluteFolder: rootDir, files: written });
  } catch (err) {
    logError('export_save_error', err);
    return res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Build a ZIP of export artifacts and return it to the browser
// Body: { baseName: string, targets: [{ name, content, mime? }] }
app.post('/api/export/zip', async (req, res) => {
  try {
    const { baseName, targets } = req.body || {};
    if (!baseName || !Array.isArray(targets) || !targets.length) {
      return res.status(400).json({ ok: false, error: { details: 'baseName and targets array are required' } });
    }
    const zip = new JSZip();
    for (const t of targets) {
      if (!t || typeof t.name !== 'string' || typeof t.content !== 'string') continue;
      const name = t.name.replace(/\\/g, '/');
      if (name.includes('..')) {
        return res.status(400).json({ ok: false, error: { details: 'Invalid file path' } });
      }
      zip.file(name, t.content);
    }
    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    const fileName = `${String(baseName)}.zip`;
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.setHeader('Content-Length', String(buf.length));
    return res.end(buf);
  } catch (err) {
    logError('export_zip_error', err);
    return res.status(500).json({ ok: false, error: { details: err.message } });
  }
});

// Logger health/ping
app.get('/api/logger/ping', (req, res) => {
  try {
    log('logger_ping', { url: req.originalUrl || req.url });
  } catch (_) {}
  let exists = false;
  try { exists = fs.existsSync(LOG_PATH); } catch (_) {}
  res.json({ ok: true, logPath: LOG_PATH, exists });
});

// Server info/status
app.get('/api/server/info', (req, res) => {
  const info = {
    pid: process.pid,
    port: Number(PORT),
    startTime: SERVER_START_TIME,
    stdoutRedirected: !process.stdout.isTTY,
    serverLogPath: SERVER_LOG_PATH,
    debugLogPath: LOG_PATH,
    logDetached: LOG_DETACHED,
    nextRotationTs: (typeof getNextRotationTs === 'function') ? getNextRotationTs() : null,
  };
  try { log('server_info', info); } catch (_) {}
  res.json({ ok: true, ...info });
});

// Release (detach) managed server.log stream and rename current file
app.post('/api/server/release-log', async (req, res) => {
  const result = { renamed: false, note: '' };
  try {
    try { detachConsoleFile(); } catch(_) {}
    try {
      if (fs.existsSync(SERVER_LOG_PATH)) {
        const releasedPath = `${SERVER_LOG_PATH}.${Date.now()}.released`;
        fs.renameSync(SERVER_LOG_PATH, releasedPath);
        result.renamed = true;
      }
    } catch (e) {
      result.note = `rename failed: ${e?.message}`;
    }
    LOG_DETACHED = true;
    log('server_release_log', { ok: true, ...result, logDetached: LOG_DETACHED });
    res.json({ ok: true, logDetached: LOG_DETACHED, ...result });
  } catch (err) {
    LOG_DETACHED = true;
    logError('server_release_log_error', err);
    res.status(500).json({ ok: false, error: { kind: 'release_failed', details: err.message }, logDetached: LOG_DETACHED, ...result });
  }
});

// Rotate managed server.log: close, rename with timestamp, reopen fresh file
app.post('/api/server/rotate-log', (req, res) => {
  try {
    const { ok, path: p } = rotateConsoleFile(SERVER_LOG_PATH);
    LOG_DETACHED = false;
    log('server_rotate_log', { ok, path: p });
    res.json({ ok: true, path: p });
  } catch (err) {
    logError('server_rotate_log_error', err);
    res.status(500).json({ ok: false, error: { kind: 'rotate_failed', details: err.message } });
  }
});


// Download current or most recent rotated server log
function getLatestRotatedLogPath() {
  try {
    const dir = __dirname;
    const files = fs.readdirSync(dir);
    const candidates = files
      .filter(f => f.startsWith('server.log.') && (f.endsWith('.released') || f.endsWith('.rotated')))
      .map(f => ({ name: f, full: path.join(dir, f), stat: fs.statSync(path.join(dir, f)) }))
      .sort((a, b) => b.stat.mtimeMs - a.stat.mtimeMs);
    return candidates.length ? candidates[0].full : null;
  } catch (_) { return null; }
}
app.get('/api/server/log/download', (req, res) => {
  try {
    let filePath = SERVER_LOG_PATH;
    if (LOG_DETACHED) {
      const latest = getLatestRotatedLogPath();
      if (latest) filePath = latest;
    }
    if (!fs.existsSync(filePath)) {
      const latest = getLatestRotatedLogPath();
      if (latest) filePath = latest;
    }
    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ ok: false, error: { kind: 'not_found', details: 'No log file available' } });
    }
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${path.basename(filePath)}"`);
    res.sendFile(filePath);
  } catch (err) {
    logError('server_log_download_error', err);
    res.status(500).json({ ok: false, error: { kind: 'download_failed', details: err.message } });
  }
});

// Tail the end of the current (or latest) server log without downloading the entire file
app.get('/api/server/log/tail', (req, res) => {
  try {
    const maxBytes = 5_000_000; // hard ceiling for safety
    const defBytes = 20_000;
    const bytes = Math.max(100, Math.min(maxBytes, Number(req.query.bytes || defBytes)));

    let filePath = SERVER_LOG_PATH;
    if (LOG_DETACHED) {
      const latest = getLatestRotatedLogPath();
      if (latest) filePath = latest;
    }
    if (!fs.existsSync(filePath)) {
      const latest = getLatestRotatedLogPath();
      if (latest) filePath = latest;
    }
    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ ok: false, error: { kind: 'not_found', details: 'No log file available' } });
    }

    const stat = fs.statSync(filePath);
    const size = stat.size;
    const start = Math.max(0, size - bytes);
    const length = size - start;

    let content = '';
    if (length > 0) {
      const fd = fs.openSync(filePath, 'r');
      try {
        const buffer = Buffer.allocUnsafe(length);
        fs.readSync(fd, buffer, 0, length, start);
        content = buffer.toString('utf8');
      } finally {
        try { fs.closeSync(fd); } catch (_) {}
      }
    }

    res.json({ ok: true, file: path.basename(filePath), size, start, bytesRead: length, truncated: start > 0, content });
  } catch (err) {
    logError('server_log_tail_error', err);
    res.status(500).json({ ok: false, error: { kind: 'tail_failed', details: err.message } });
  }
});


// Graceful shutdown (frontend should show offline state after this)
app.post('/api/server/shutdown', (req, res) => {
  try { log('server_shutdown_requested', { from: req.ip || 'unknown' }); } catch (_) {}
  res.json({ ok: true, message: 'Shutting down…' });
  setTimeout(() => process.exit(0), 150);
});

// Restart: close all sessions, spawn start.bat in detached mode, then exit current process
app.post('/api/server/restart', async (req, res) => {
  const { spawn } = require('child_process');
  const startBatPath = path.join(__dirname, 'start.bat');

  try {
    log('server_restart_requested', { from: req.ip || 'unknown', startBatPath });

    // Check if start.bat exists
    if (!fs.existsSync(startBatPath)) {
      return res.status(500).json({
        ok: false,
        error: { kind: 'restart_failed', details: 'start.bat not found' }
      });
    }

    // Close all active MCP sessions before restarting
    try {
      const closeResult = await closeAllSessions();
      log('server_restart_sessions_closed', { closedCount: closeResult.closed.length });
    } catch (sessionErr) {
      logError('server_restart_session_close_error', sessionErr);
      // Continue with restart even if session close fails
    }

    // Spawn start.bat in detached mode so it survives parent exit
    const child = spawn('cmd.exe', ['/c', startBatPath], {
      detached: true,
      stdio: 'ignore',
      cwd: __dirname
    });

    // Unref so parent can exit independently
    child.unref();

    log('server_restart_spawned', { pid: child.pid });
    res.json({ ok: true, message: 'Restarting server…' });

    // Exit current process (kills all child MCP sessions)
    // The spawned start.bat will clean ports and start fresh
    setTimeout(() => process.exit(0), 150);
  } catch (err) {
    logError('server_restart_error', err);
    res.status(500).json({
      ok: false,
      error: { kind: 'restart_failed', details: err.message }
    });
  }
});

// Expose recent in-memory debug entries for immediate inspection
app.get('/api/logger/recent', (req, res) => {
  const limit = Number(req.query.limit || 200);
  const items = getRecent(limit);
  res.json({ ok: true, items });
});

// API route for removing a server from the current config
app.post('/api/config/remove-server', async (req, res) => {
  const { baseConfig, serverName } = req.body || {};
  if (!baseConfig || typeof baseConfig !== 'object') {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'baseConfig is required' } });
  }
  if (!serverName || typeof serverName !== 'string') {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'serverName is required' } });
  }
  try {
    const normalizedBase = JSON.parse(JSON.stringify(baseConfig));
    const reduced = removeServerFromConfig(normalizedBase, serverName);
    const results = await diagnoseConfigEntries(reduced);
    const servers = attachConfigMetadata(reduced, results);
    res.json({ ok: true, config: reduced, servers });
  } catch (err) {
    const status =
      err.code && (err.code.startsWith('CONFIG_') || err.code === 'CONFIG_NOT_FOUND') ? 400 : 500;
    res.status(status).json({ ok: false, error: { kind: 'config_remove_error', details: err.message } });
  }
});

// API route for testing individual tools
app.post('/api/tools/call', async (req, res) => {
  const { spec, toolName, toolArgs, keepSessionOpen } = req.body || {};
  const debugMsg1 = `[DEBUG] /api/tools/call - toolName: ${toolName}, keepSessionOpen: ${keepSessionOpen}`;
  try { process.stdout.write(debugMsg1 + "\n"); } catch(_) {}
  try { process.stderr.write(debugMsg1 + "\n"); } catch(_) {}
  log('tools_call_request', {
    toolName,
    keepSessionOpen: !!keepSessionOpen,
    spec: spec ? { mode: spec.mode, command: spec.command, url: spec.url, args: spec.args } : null,
    args: toolArgs
  });
  if (!spec || typeof spec !== 'object' || !spec.mode) {
    return res.status(400).json({ error: 'spec with a valid mode is required' });
  }
  if (!toolName || typeof toolName !== 'string') {
    return res.status(400).json({ error: 'toolName is required' });
  }
  try {
    const result = await callTool(spec, toolName, toolArgs ?? {}, { keepSessionOpen: keepSessionOpen ?? false });
    const debugMsg2 = `[DEBUG] callTool result - ok: ${result.ok}, sessionId: ${result.sessionId}, sessionReused: ${result.sessionReused}`;
    try { process.stdout.write(debugMsg2 + "\n"); } catch(_) {}
    try { process.stderr.write(debugMsg2 + "\n"); } catch(_) {}

    // Enhanced logging with tool output (truncated for console, full in file)
    logWithTruncation('tools_call_response', {
      ok: result?.ok,
      toolName,
      sessionId: result?.sessionId || null,
      sessionReused: !!result?.sessionReused,
      transport: result?.transport || null,
      error: result?.error?.kind || null,
      output: result?.output,  // Include the actual tool output
      handshake: result?.handshake,
      endedAt: new Date().toISOString()
    }, 1000);  // Truncate console output at 1000 chars

    res.json(result);
  } catch (err) {
    try { process.stderr.write(`[DEBUG] callTool error: ${err?.message}\n`); } catch(_) {}
    logError('tools_call_error', err, { toolName, endedAt: new Date().toISOString() });
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for running a tool and saving a markdown report identical to UI
app.post('/api/tools/report', async (req, res) => {
  const { spec, toolName, toolArgs, keepSessionOpen, savePath, filename } = req.body || {};
  if (!spec || typeof spec !== 'object' || !spec.mode) {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'spec with a valid mode is required' } });
  }
  if (!toolName || typeof toolName !== 'string') {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'toolName is required' } });
  }
  const startedAt = new Date();
  try {
    log('tools_report_request', { toolName, keepSessionOpen: !!keepSessionOpen });
    const callResult = await callTool(spec, toolName, toolArgs ?? {}, { keepSessionOpen: !!keepSessionOpen });
    const endedAt = new Date();
    const timings = { startedAt: startedAt.toISOString(), endedAt: endedAt.toISOString(), durationMs: endedAt.getTime() - startedAt.getTime() };
    const md = renderToolReportMarkdown({ spec, toolName, toolArgs: toolArgs ?? {}, result: callResult, timings });

    // Determine filename and path
    const ts = new Date().toISOString().replace(/[:.]/g, '').replace('T', '_').replace('Z', '');
    const specLabel = (() => {
      if (spec.mode === 'http') return (spec.url || 'http').replace(/[^a-z0-9._-]+/gi, '_');
      const cmd = (spec.command || 'stdio').replace(/[^a-z0-9._-]+/gi, '_');
      return cmd;
    })();
    const safeTool = toolName.replace(/[^a-z0-9._-]+/gi, '_');
    const finalName = filename && typeof filename === 'string' && filename.trim()
      ? filename.trim()
      : `MCPDiagnois_Report_${ts}_${specLabel}_${safeTool}.md`;
    const dir = savePath && typeof savePath === 'string' && savePath.trim() ? savePath.trim() : __dirname;
    const outPath = path.isAbsolute(finalName) ? finalName : path.join(dir, finalName);

    fs.writeFileSync(outPath, md, { encoding: 'utf8' });
    log('tools_report_saved', { path: outPath, bytes: Buffer.byteLength(md, 'utf8') });
    res.json({ ok: true, path: outPath, content: md, callResult });
  } catch (err) {
    logError('tools_report_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for listing active sessions
app.get('/api/sessions', async (req, res) => {
  try {
    const sessions = listSessions();
    log('sessions_list', { count: sessions.length, sessions });
    res.json({ ok: true, sessions });
  } catch (err) {
    logError('sessions_list_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for closing a specific session
app.post('/api/sessions/close', async (req, res) => {
  const { sessionId } = req.body || {};
  if (!sessionId || typeof sessionId !== 'string') {
    return res.status(400).json({ error: 'sessionId is required' });
  }
  try {
    log('session_close_request', { sessionId });
    const result = await closeSession(sessionId);
    log('session_close_response', { sessionId, ok: result.ok, error: result.error || null });
    res.json(result);
  } catch (err) {
    logError('session_close_error', err, { sessionId });
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for closing all sessions
app.post('/api/sessions/close-all', async (req, res) => {
  try {
    log('session_close_all_request', {});
    const result = await closeAllSessions();
    log('session_close_all_response', result);
    res.json({ ok: true, ...result });
  } catch (err) {
    logError('session_close_all_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for proactively opening (or reusing) a kept-alive session for a spec
app.post('/api/sessions/open', async (req, res) => {
  const { spec } = req.body || {};
  if (!spec || typeof spec !== 'object' || !spec.mode) {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'spec with a valid mode is required' } });
  }
  try {
    log('session_open_request', { spec: { mode: spec.mode, command: spec.command, url: spec.url, args: spec.args } });
    const opened = await openSessionForSpec(spec);
    log('session_open_response', { sessionId: opened.sessionId, reused: opened.sessionReused, transport: opened.transport });
    res.json(opened);
  } catch (err) {
    logError('session_open_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// API route for restarting a session by spec or sessionId
app.post('/api/sessions/restart', async (req, res) => {
  const { spec, sessionId } = req.body || {};
  if (!sessionId && !(spec && typeof spec === 'object' && spec.mode)) {
    return res.status(400).json({ ok: false, error: { kind: 'invalid_request', details: 'Provide sessionId or spec with a valid mode' } });
  }
  try {
    log('session_restart_request', { sessionId: sessionId || null, spec: spec ? { mode: spec.mode, command: spec.command, url: spec.url, args: spec.args } : null });
    const restarted = await restartSessionForSpec({ sessionId, spec });
    log('session_restart_response', { sessionId: restarted.sessionId, closedCount: restarted.closedCount, transport: restarted.transport });
    res.json(restarted);
  } catch (err) {
    logError('session_restart_error', err);
    res.status(500).json({ ok: false, error: { kind: 'internal_error', details: err.message } });
  }
});

// Serve static files from the public directory
const publicDir = path.join(__dirname, 'public');
app.use(express.static(publicDir));

// Fallback to index.html for any other route (supports client‑side routing if needed)
app.get('*', (_req, res) => {
  res.sendFile(path.join(publicDir, 'index.html'));
});

// Start the server
app.listen(PORT, () => {
  console.log(`MCP diagnosis UI server is running on http://localhost:${PORT}`);
  log('server_listening', { port: Number(PORT) });
  // Optional self-tests (disabled by default). Enable by setting MCP_SELFTEST=1 or MCP_SELFTEST=true
  const selftestFlag = String(process.env.MCP_SELFTEST || '').toLowerCase();
  const enableSelftest = selftestFlag === '1' || selftestFlag === 'true';
  if (enableSelftest) {
    log('selftest_scheduled', { delayMs: 1500 });
    setTimeout(runSelfTestLogging, 1500);
    log('selftest_followup_scheduled', { delayMs: 4500 });
    setTimeout(runSelfTestFollowUp, 4500);
  } else {
    log('selftest_skipped', { reason: 'disabled', env: process.env.MCP_SELFTEST || null });
  }
});

// Global unhandled error logging
process.on('uncaughtException', (err) => {
  try { logError('uncaught_exception', err); } catch (_) {}
});
process.on('unhandledRejection', (reason) => {
  try { logError('unhandled_rejection', reason instanceof Error ? reason : new Error(String(reason))); } catch (_) {}
});

// ---- Self-test: invoke a tool call to produce logs ----
async function runSelfTestLogging() {
  try {
    try { process.stdout.write('[DEBUG] selftest_begin\n'); } catch(_) {}
    const spec = {
      mode: 'stdio',
      command: 'npx',
      args: [
        '-y',
        '@playwright/mcp@latest',
        '--output-dir', 'C:/Users/jenss/ONEDRI~2/Code/Test/.evidence/screenshots',
        '--save-session', '--save-trace',
        '--browser', 'chrome',
        '--viewport-size', '2400,1350',
        '--isolated', '--no-sandbox'
      ]
    };
    log('selftest_begin', {});
    // Intentionally call a non-existing tool to force error path while exercising connect/session
    const result = await callTool(spec, 'nonexistent_tool_for_logging', {}, { keepSessionOpen: false });
    log('selftest_result', { ok: result?.ok, sessionId: result?.sessionId || null, transport: result?.transport || null });
    try { process.stdout.write(`[DEBUG] selftest_done ok=${result?.ok}\n`); } catch(_) {}
  } catch (err) {
    try { process.stderr.write(`[DEBUG] selftest_error ${err?.message}\n`); } catch(_) {}
    logError('selftest_error', err);
  }
}

async function runSelfTestFollowUp() {
  try {
    try { process.stdout.write('[DEBUG] selftest_followup_begin\n'); } catch(_) {}
    const spec = {
      mode: 'stdio',
      command: 'npx',
      args: [
        '-y',
        '@playwright/mcp@latest',
        '--output-dir', 'C:/Users/jenss/ONEDRI~2/Code/Test/.evidence/screenshots',
        '--save-session', '--save-trace',
        '--browser', 'chrome',
        '--viewport-size', '2400,1350',
        '--isolated', '--no-sandbox'
      ]
    };
    log('selftest_followup_begin', {});
    const result = await callTool(spec, 'browser_snapshot', {}, { keepSessionOpen: false });
    log('selftest_followup_result', { ok: result?.ok, sessionId: result?.sessionId || null, transport: result?.transport || null });
    try { process.stdout.write(`[DEBUG] selftest_followup_done ok=${result?.ok}\n`); } catch(_) {}
  } catch (err) {
    try { process.stderr.write(`[DEBUG] selftest_followup_error ${err?.message}\n`); } catch(_) {}
    logError('selftest_followup_error', err);
  }
}

function attachConfigMetadata(normalized, results) {
  const map = new Map();
  (normalized.servers || []).forEach((server) => {
    map.set(server.name, server);
  });
  return results.map((item) => {
    const configEntry = map.get(item.name);
    const snippetJson = configEntry ? serializeServerSnippet(configEntry, 'json') : null;
    const snippetToml = configEntry ? serializeServerSnippet(configEntry, 'toml') : null;
    const defaultSnippet =
      normalized.format === 'toml'
        ? snippetToml ?? snippetJson
        : snippetJson ?? snippetToml;
    return {
      ...item,
      configEntry: configEntry ? JSON.parse(JSON.stringify(configEntry)) : null,
      configSnippet: defaultSnippet,
      configSnippets: {
        json: snippetJson,
        toml: snippetToml
      },
      configFormat: normalized.format
    };
  });
}
