/* --- combined server config snippets (as shown in UI) ---
--- server: playwright ---
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": [
        "-y",
        "@playwright/mcp@latest",
        "--config",
        "C:/Users/jenss/ONEDRI~2/Code/Test/mcpconfig/subconfigs/plwghtconfig_cognitive.json"
      ]
    }
  }
}
--- end snippets --- */

// Preamble: attempt to resolve @modelcontextprotocol/sdk when the exported script is run outside the original project.
(function(){
  const path = require('path');
  const fs = require('fs');
  function tryRequire(p){ try { return require(p); } catch(e) { return null; } }
  let _Client = tryRequire('@modelcontextprotocol/sdk/client/index.js');
  let _Stdio = tryRequire('@modelcontextprotocol/sdk/client/stdio.js');
  let _Streamable = tryRequire('@modelcontextprotocol/sdk/client/streamableHttp.js');
  let _SSE = tryRequire('@modelcontextprotocol/sdk/client/sse.js');
  if (!(_Client && _Stdio && _Streamable && _SSE)) {
    try {
      const { createRequire } = require('module');
      let dir = __dirname;
      while (true) {
        try {
          const pj = path.join(dir, 'package.json');
          if (fs.existsSync(pj)) {
            const req = createRequire(pj);
            try {
              _Client = _Client || tryRequire.call(null, req.resolve('@modelcontextprotocol/sdk/client/index.js')) || req('@modelcontextprotocol/sdk/client/index.js');
            } catch(_) { _Client = _Client || req('@modelcontextprotocol/sdk/client/index.js'); }
            _Stdio = _Stdio || req('@modelcontextprotocol/sdk/client/stdio.js');
            _Streamable = _Streamable || req('@modelcontextprotocol/sdk/client/streamableHttp.js');
            _SSE = _SSE || req('@modelcontextprotocol/sdk/client/sse.js');
            break;
          }
        } catch(_) { }
        const parent = path.dirname(dir);
        if (parent === dir) break;
        dir = parent;
      }
    } catch(_) { }
  }
  if (!(_Client && _Stdio && _Streamable && _SSE)) {
    console.error('Cannot find @modelcontextprotocol/sdk. Run using the project wrapper (scripts/run_exported_test.js) or install the package in this folder.');
    process.exit(1);
  }
  // expose resolved modules to outer scope
  global.__mcp_export_client_module__ = {
    Client: _Client.Client || _Client,
    StdioClientTransport: _Stdio.StdioClientTransport || _Stdio,
    StreamableHTTPClientTransport: _Streamable.StreamableHTTPClientTransport || _Streamable,
    SSEClientTransport: _SSE.SSEClientTransport || _SSE
  };
})();
const { Client } = global.__mcp_export_client_module__;
const { StdioClientTransport } = global.__mcp_export_client_module__;
const { StreamableHTTPClientTransport } = global.__mcp_export_client_module__;
const { SSEClientTransport } = global.__mcp_export_client_module__;

// Generated by MCP Diagnosis Tool: Multi-server workflow replay (v 1.2.1.16)
// Exported with MCP Diagnosis Tool v 1.2.1.16

const servers = [
  {
    "name": "playwright",
    "spec": {
      "mode": "stdio",
      "command": "npx",
      "args": [
        "-y",
        "@playwright/mcp@latest",
        "--config",
        "C:/Users/jenss/ONEDRI~2/Code/Test/mcpconfig/subconfigs/plwghtconfig_cognitive.json"
      ]
    }
  }
];
const steps = [
  {
    "server": "playwright",
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3060/"
    },
    "keep_session_open": true,
    "started_at": "2025-11-02T20:45:39.650Z",
    "finished_at": "2025-11-02T20:45:42.044Z",
    "ok": true,
    "warmup": false
  },
  {
    "server": "playwright",
    "tool": "browser_click",
    "args": {
      "element": "Keep session open",
      "ref": "e35",
      "button": "left"
    },
    "keep_session_open": true,
    "started_at": "2025-11-02T20:46:51.414Z",
    "finished_at": "2025-11-02T20:46:52.550Z",
    "ok": true,
    "warmup": false
  },
  {
    "server": "playwright",
    "tool": "browser_click",
    "args": {
      "element": "expand playwright codegen",
      "ref": "e63",
      "button": "left"
    },
    "keep_session_open": true,
    "started_at": "2025-11-02T20:47:33.635Z",
    "finished_at": "2025-11-02T20:47:34.704Z",
    "ok": true,
    "warmup": false
  },
  {
    "server": "playwright",
    "tool": "browser_type",
    "args": {
      "element": "url",
      "ref": "e69",
      "text": "http://localhost:3002/zertifikat",
      "submit": true
    },
    "keep_session_open": true,
    "started_at": "2025-11-02T20:48:52.668Z",
    "finished_at": "2025-11-02T20:48:53.726Z",
    "ok": true,
    "warmup": false
  },
  {
    "server": "playwright",
    "tool": "browser_click",
    "args": {
      "element": "codegen start",
      "ref": "e70",
      "button": "left"
    },
    "keep_session_open": true,
    "started_at": "2025-11-02T20:49:20.690Z",
    "finished_at": "2025-11-02T20:49:20.748Z",
    "ok": true,
    "warmup": false
  }
];

const clients = new Map();

function toJsonable(x){
  if (x == null) return x;
  const t = typeof x;
  if (t === 'string' || t === 'number' || t === 'boolean') return x;
  if (Array.isArray(x)) return x.map(toJsonable);
  if (t === 'object') {
    if (x.type && (x.text !== undefined || x.data !== undefined || x.mimeType !== undefined || x.name !== undefined || x.error !== undefined || x.url !== undefined || x.path !== undefined)) {
      const out = { type: x.type };
      for (const k of ['text','data','mimeType','name','error','url','path']) { if (Object.prototype.hasOwnProperty.call(x, k)) out[k] = toJsonable(x[k]); }
      return out;
    }
    const out = {}; for (const [k, v] of Object.entries(x)) out[k] = toJsonable(v); return out;
  }
  return String(x);
}

async function getClient(serverName) {
  if (clients.has(serverName)) return clients.get(serverName);
  const serverDef = servers.find(s => s.name === serverName);
  if (!serverDef) throw new Error('Unknown server: ' + serverName);
  const spec = serverDef.spec;
  const client = new Client({ name: 'mcp-workflow-replay', version: '1.0.0' });
  if (spec.mode === 'stdio') {
    const transport = new StdioClientTransport({
      command: spec.command,
      args: spec.args || [],
      env: spec.env || {},
      cwd: spec.cwd,
      stderr: spec.stderr
    });
    await client.connect(transport);
  } else if (spec.mode === 'http') {
    const url = new URL(spec.url);
    try {
      const http = new StreamableHTTPClientTransport(url);
      await client.connect(http);
    } catch (_) {
      const sse = new SSEClientTransport(url);
      await client.connect(sse);
    }
  } else {
    throw new Error('Unknown spec.mode: ' + spec.mode);
  }
  clients.set(serverName, client);
  return client;
}

async function closeClient(serverName) {
  const client = clients.get(serverName);
  if (client) {
    try { await client.close(); } catch {}
    clients.delete(serverName);
  }
}

async function closeAllClients() {
  for (const [name] of clients) {
    await closeClient(name);
  }
}

async function run() {
  try {
    for (const s of steps) {
      const client = await getClient(s.server);
      const result = await client.callTool({ name: s.tool, arguments: s.args || {} });
      const payload = (result && (result.content ?? result)) ?? null;
      console.log('[' + s.server + '] tool', s.tool, '->\n' + JSON.stringify(toJsonable(payload), null, 2));
      if (!s.keep_session_open) {
        await closeClient(s.server);
      }
    }
  } finally {
    await closeAllClients();
  }
}

run().catch(err => { console.error('Run failed:', err); process.exit(1); });
