/* Generated by MCP Diagnosis Tool: Multi-server workflow replay */
// Requires: npm i @modelcontextprotocol/sdk
const { Client } = require('@modelcontextprotocol/sdk/client/index.js');
const { StdioClientTransport } = require('@modelcontextprotocol/sdk/client/stdio.js');
const { StreamableHTTPClientTransport } = require('@modelcontextprotocol/sdk/client/streamableHttp.js');
const { SSEClientTransport } = require('@modelcontextprotocol/sdk/client/sse.js');

const servers = [
  {
    "name": "playwright",
    "spec": {
      "mode": "stdio",
      "command": "npx",
      "args": [
        "-y",
        "@playwright/mcp@latest",
        "--output-dir",
        "C:/Users/jenss/OneDrive - Singularyt UG/Code/Test/.evidence/screenshots",
        "--save-session",
        "--save-trace",
        "--browser",
        "chrome",
        "--viewport-size",
        "2400,1350",
        "--isolated",
        "--no-sandbox"
      ],
      "env": {
        "PLAYWRIGHT_BROWSERS_PATH": "0"
      }
    }
  }
];
const steps = [
  {
    "server": "playwright",
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3002/"
    },
    "keep_session_open": true,
    "started_at": "2025-11-01T06:02:27.947Z",
    "finished_at": "2025-11-01T06:02:30.355Z",
    "ok": true,
    "warmup": false
  }
];

const clients = new Map();

function toJsonable(x){
  if (x == null) return x;
  const t = typeof x;
  if (t === 'string' || t === 'number' || t === 'boolean') return x;
  if (Array.isArray(x)) return x.map(toJsonable);
  if (t === 'object') {
    if (x.type && (x.text !== undefined || x.data !== undefined || x.mimeType !== undefined || x.name !== undefined || x.error !== undefined || x.url !== undefined || x.path !== undefined)) {
      const out = { type: x.type };
      for (const k of ['text','data','mimeType','name','error','url','path']) { if (Object.prototype.hasOwnProperty.call(x, k)) out[k] = toJsonable(x[k]); }
      return out;
    }
    const out = {}; for (const [k, v] of Object.entries(x)) out[k] = toJsonable(v); return out;
  }
  return String(x);
}

async function getClient(serverName) {
  if (clients.has(serverName)) return clients.get(serverName);
  const serverDef = servers.find(s => s.name === serverName);
  if (!serverDef) throw new Error('Unknown server: ' + serverName);
  const spec = serverDef.spec;
  const client = new Client({ name: 'mcp-workflow-replay', version: '1.0.0' });
  if (spec.mode === 'stdio') {
    const transport = new StdioClientTransport({
      command: spec.command,
      args: spec.args || [],
      env: spec.env || {},
      cwd: spec.cwd,
      stderr: spec.stderr
    });
    await client.connect(transport);
  } else if (spec.mode === 'http') {
    const url = new URL(spec.url);
    try {
      const http = new StreamableHTTPClientTransport(url);
      await client.connect(http);
    } catch (_) {
      const sse = new SSEClientTransport(url);
      await client.connect(sse);
    }
  } else {
    throw new Error('Unknown spec.mode: ' + spec.mode);
  }
  clients.set(serverName, client);
  return client;
}

async function closeClient(serverName) {
  const client = clients.get(serverName);
  if (client) {
    try { await client.close(); } catch {}
    clients.delete(serverName);
  }
}

async function closeAllClients() {
  for (const [name] of clients) {
    await closeClient(name);
  }
}

async function run() {
  try {
    for (const s of steps) {
      const client = await getClient(s.server);
      const result = await client.callTool({ name: s.tool, arguments: s.args || {} });
      const payload = (result && (result.content ?? result)) ?? null;
      console.log('[' + s.server + '] tool', s.tool, '->\n' + JSON.stringify(toJsonable(payload), null, 2));
      if (!s.keep_session_open) {
        await closeClient(s.server);
      }
    }
  } finally {
    await closeAllClients();
  }
}

run().catch(err => { console.error('Run failed:', err); process.exit(1); });
