# Generated by MCP Diagnosis Tool: Multi-server workflow replay
# Requires: pip install mcp
import asyncio, json
from contextlib import AsyncExitStack
from mcp import ClientSession
from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.streamable_http import streamablehttp_client

servers = [
  {
    "name": "playwright",
    "spec": {}
  },
  {
    "name": "cognitive-visual-analytics",
    "spec": {}
  }
]
steps = [
  {
    "server": "playwright",
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3002/"
    },
    "keep_session_open": true,
    "started_at": "2025-10-24T01:11:16.592Z",
    "finished_at": "2025-10-24T01:11:16.918Z",
    "ok": true,
    "warmup": false
  },
  {
    "server": "cognitive-visual-analytics",
    "tool": "cognitive_visual_dimensions",
    "args": {},
    "keep_session_open": true,
    "started_at": "2025-10-24T01:11:52.074Z",
    "finished_at": "2025-10-24T01:11:52.103Z",
    "ok": true,
    "warmup": false
  }
]

sessions = {}
exit_stack = AsyncExitStack()

def to_jsonable(x):
    import dataclasses
    if x is None or isinstance(x, (str, int, float, bool)):
        return x
    if isinstance(x, (list, tuple)):
        return [to_jsonable(i) for i in x]
    if isinstance(x, dict):
        return {str(k): to_jsonable(v) for k, v in x.items()}
    t = getattr(x, 'type', None)
    if t:
        out = {'type': t}
        for attr in ('text','data','mimeType','name','error','url','path'):
            if hasattr(x, attr):
                out[attr] = getattr(x, attr)
        return out
    if dataclasses.is_dataclass(x):
        return to_jsonable(dataclasses.asdict(x))
    d = getattr(x, '__dict__', None)
    if d is not None:
        return {k: to_jsonable(v) for k, v in d.items()}
    return str(x)

async def get_session(server_name):
    if server_name in sessions:
        return sessions[server_name]
    server_def = next((s for s in servers if s['name'] == server_name), None)
    if not server_def:
        raise ValueError(f'Unknown server: {server_name}')
    spec = server_def['spec']
    await exit_stack.__aenter__()
    if spec.get('mode') == 'stdio':
        params = StdioServerParameters(command=spec.get('command'), args=spec.get('args') or [], env=spec.get('env') or None)
        read, write = await exit_stack.enter_async_context(stdio_client(params))
        sess = await exit_stack.enter_async_context(ClientSession(read, write))
    elif spec.get('mode') == 'http':
        url = spec.get('url')
        read, write = await exit_stack.enter_async_context(streamablehttp_client(url))
        sess = await exit_stack.enter_async_context(ClientSession(read, write))
    else:
        raise ValueError(f"Unknown mode: {spec.get('mode')}")
    sessions[server_name] = sess
    return sess

async def close_session(server_name):
    if server_name in sessions:
        del sessions[server_name]

async def close_all_sessions():
    sessions.clear()
    await exit_stack.__aexit__(None, None, None)

async def main():
    try:
        for s in steps:
            sess = await get_session(s['server'])
            result = await sess.call_tool(s['tool'], s.get('args') or {})
            payload = getattr(result, 'content', None) or getattr(result, 'result', None)
            print(f"[{s['server']}] tool {s['tool']} ->", json.dumps(to_jsonable(payload), ensure_ascii=False))
            if not bool(s.get('keep_session_open', False)):
                await close_session(s['server'])
    finally:
        await close_all_sessions()

if __name__ == '__main__':
    asyncio.run(main())
