# Generated by MCP Diagnosis Tool
import os, json, requests
BASE_URL = os.getenv('MCP_DOCTOR_URL', 'http://localhost:3000')
spec = {
  "mode": "stdio",
  "command": "npx",
  "args": [
    "-y",
    "@playwright/mcp@latest",
    "--output-dir",
    "C:/Users/jenss/ONEDRI~2/Code/Test/.evidence/screenshots",
    "--save-session",
    "--save-trace",
    "--browser",
    "chrome",
    "--viewport-size",
    "2400,1350",
    "--isolated",
    "--no-sandbox"
  ],
  "env": {
    "PLAYWRIGHT_BROWSERS_PATH": "0"
  }
}
steps = [
  {
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3002/"
    },
    "keep_session_open": true,
    "started_at": "2025-10-22T14:00:11.994Z",
    "finished_at": "2025-10-22T14:00:15.588Z",
    "ok": true,
    "warmup": false
  },
  {
    "tool": "browser_snapshot",
    "args": {},
    "keep_session_open": true,
    "started_at": "2025-10-22T14:00:36.567Z",
    "finished_at": "2025-10-22T14:00:36.588Z",
    "ok": true,
    "warmup": false
  }
]
for s in steps:
    r = requests.post(f"{BASE_URL}/api/tools/call", json={
        "spec": spec,
        "toolName": s["tool"],
        "toolArgs": s.get("args", {}),
        "keepSessionOpen": bool(s.get("keep_session_open", False))
    })
    try:
        data = r.json()
    except Exception:
        data = {"ok": False, "error": {"details": r.text}}
    print("tool", s["tool"], "ok=", data.get("ok"))
    if not r.ok:
        raise SystemExit(1)
