/* Generated by MCP Diagnosis Tool */
const BASE_URL = process.env.MCP_DOCTOR_URL || 'http://localhost:3000';
const spec = {
  "mode": "stdio",
  "command": "npx",
  "args": [
    "-y",
    "@playwright/mcp@latest",
    "--output-dir",
    "C:/Users/jenss/ONEDRI~2/Code/Test/.evidence/screenshots",
    "--save-session",
    "--save-trace",
    "--browser",
    "chrome",
    "--viewport-size",
    "2400,1350",
    "--isolated",
    "--no-sandbox"
  ],
  "env": {
    "PLAYWRIGHT_BROWSERS_PATH": "0"
  }
};
const steps = [
  {
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3002/"
    },
    "keep_session_open": true,
    "started_at": "2025-10-22T14:00:11.994Z",
    "finished_at": "2025-10-22T14:00:15.588Z",
    "ok": true,
    "warmup": false
  },
  {
    "tool": "browser_snapshot",
    "args": {},
    "keep_session_open": true,
    "started_at": "2025-10-22T14:00:36.567Z",
    "finished_at": "2025-10-22T14:00:36.588Z",
    "ok": true,
    "warmup": false
  }
];
async function run(){
  for (const s of steps){
    const res = await fetch(`${BASE_URL}/api/tools/call`, {
      method:'POST', headers:{'Content-Type':'application/json'},
      body: JSON.stringify({ spec, toolName: s.tool, toolArgs: s.args || {}, keepSessionOpen: !!s.keep_session_open })
    });
    let data;
    try { data = await res.json(); } catch { data = { ok: false }; }
    console.log('tool', s.tool, 'ok=', data.ok, 'sessionId=', data.sessionId || null);
    if (!res.ok) throw new Error(JSON.stringify(data));
  }
}
run().catch(err=>{ console.error('Run failed:', err); process.exit(1); });
