/* Generated by MCP Diagnosis Tool: direct MCP client replay (Option A) */
// Requires: npm i @modelcontextprotocol/sdk
const { Client } = require('@modelcontextprotocol/sdk/client/index.js');
const { StdioClientTransport } = require('@modelcontextprotocol/sdk/client/stdio.js');
const { StreamableHTTPClientTransport } = require('@modelcontextprotocol/sdk/client/streamableHttp.js');
const { SSEClientTransport } = require('@modelcontextprotocol/sdk/client/sse.js');

// Playwright MCP spec (stdio)
const spec = {
  mode: 'stdio',
  command: 'npx',
  args: [
    '-y',
    '@playwright/mcp@latest',
    '--output-dir',
    'C:/Users/jenss/ONEDRI~2/Code/Test/.evidence/screenshots',
    '--save-session',
    '--save-trace',
    '--browser', 'chrome',
    '--viewport-size', '2400,1350',
    '--no-sandbox',
    '--isolated'
  ],
  env: { PLAYWRIGHT_BROWSERS_PATH: '0' }
};

// Recorded steps (Option A)
const steps = [
  { tool: 'browser_navigate', args: { url: 'http://localhost:3002/' }, keep_session_open: true },
  { tool: 'browser_type', args: { ref: 'e22', element: 'e22', text: 'admin' }, keep_session_open: true },
  { tool: 'browser_type', args: { ref: 'e25', element: 'e25', text: 'admin123' }, keep_session_open: true },
  { tool: 'browser_click', args: { ref: 'e27', element: 'e27', button: 'left' }, keep_session_open: true },
  { tool: 'browser_snapshot', args: {}, keep_session_open: true }
];

let client = null;
async function ensureClient() {
  if (client) return client;
  client = new Client({ name: 'mcp-session-replay', version: '1.0.0' });
  if (spec.mode === 'stdio') {
    const transport = new StdioClientTransport({
      command: spec.command,
      args: spec.args || [],
      env: spec.env || {},
      cwd: spec.cwd,
      stderr: spec.stderr
    });
    await client.connect(transport);
  } else if (spec.mode === 'http') {
    const url = new URL(spec.url);
    try {
      const http = new StreamableHTTPClientTransport(url);
      await client.connect(http);
    } catch (_) {
      const sse = new SSEClientTransport(url);
      await client.connect(sse);
    }
  } else {
    throw new Error('Unknown spec.mode: ' + spec.mode);
  }
  return client;
}

// Safe conversion of MCP results to JSON-serializable structures (mirrors Python export)
function toJsonable(x) {
  if (x == null) return x;
  const t = typeof x;
  if (t === 'string' || t === 'number' || t === 'boolean') return x;
  if (Array.isArray(x)) return x.map(toJsonable);
  if (t === 'object') {
    if (x.type && (x.text !== undefined || x.data !== undefined || x.mimeType !== undefined || x.name !== undefined || x.error !== undefined || x.url !== undefined || x.path !== undefined)) {
      const out = { type: x.type };
      for (const k of ['text','data','mimeType','name','error','url','path']) {
        if (Object.prototype.hasOwnProperty.call(x, k)) out[k] = toJsonable(x[k]);
      }
      return out;
    }
    const out = {};
    for (const [k, v] of Object.entries(x)) out[k] = toJsonable(v);
    return out;
  }
  return String(x);
}


// Graceful shutdown on signals (best effort)
for (const sig of ['SIGINT','SIGTERM']) {
  process.on(sig, () => {
    closeClient().finally(() => process.exit(sig === 'SIGINT' ? 130 : 143));
  });
}


async function closeClient() {
  if (client) {
    try { await client.close(); } catch {}
    client = null;
  }
}

async function run() {
  try {
    for (const s of steps) {
      const c = await ensureClient();
      const result = await c.callTool({ name: s.tool, arguments: s.args || {} });
      const payload = (result && (result.content ?? result)) ?? null;
      console.log('tool', s.tool, '->\n' + JSON.stringify(toJsonable(payload), null, 2));
      if (!s.keep_session_open) {
        await closeClient();
      }
    }
  } finally {
    await closeClient();
  }
}

run().catch(err => { console.error('Run failed:', err); process.exit(1); });

