# Generated by MCP Diagnosis Tool: direct MCP client replay
# Requires: pip install mcp
import asyncio, json
from contextlib import AsyncExitStack
from mcp import ClientSession
from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.streamable_http import streamablehttp_client

spec = {
  "mode": "stdio",
  "command": "npx",
  "args": [
    "-y",
    "@playwright/mcp@latest",
    "--config",
    "C:/Users/jenss/ONEDRI~2/Code/Test/mcpconfig/subconfigs/plwghtconfig.json"
  ]
}
steps = [
  {
    "tool": "browser_navigate",
    "args": {
      "url": "http://localhost:3002/"
    },
    "keep_session_open": true,
    "started_at": "2025-10-23T21:07:40.297Z",
    "finished_at": "2025-10-23T21:07:42.730Z",
    "ok": true,
    "warmup": false
  }
]

session = None
exit_stack = AsyncExitStack()

def to_jsonable(x):
    import dataclasses
    if x is None or isinstance(x, (str, int, float, bool)):
        return x
    if isinstance(x, (list, tuple)):
        return [to_jsonable(i) for i in x]
    if isinstance(x, dict):
        return {str(k): to_jsonable(v) for k, v in x.items()}
    t = getattr(x, 'type', None)
    if t:
        out = {'type': t}
        for attr in ('text','data','mimeType','name','error','url','path'):
            if hasattr(x, attr):
                out[attr] = getattr(x, attr)
        return out
    if dataclasses.is_dataclass(x):
        return to_jsonable(dataclasses.asdict(x))
    d = getattr(x, '__dict__', None)
    if d is not None:
        return {k: to_jsonable(v) for k, v in d.items()}
    return str(x)

async def ensure_session():
    global session
    if session is not None:
        return session
    await exit_stack.__aenter__()
    if spec.get('mode') == 'stdio':
        params = StdioServerParameters(command=spec.get('command'), args=spec.get('args') or [], env=spec.get('env') or None)
        read, write = await exit_stack.enter_async_context(stdio_client(params))
        sess = await exit_stack.enter_async_context(ClientSession(read, write))
    elif spec.get('mode') == 'http':
        url = spec.get('url')
        if not url:
            raise RuntimeError('Missing spec.url for http mode')
        read, write = await exit_stack.enter_async_context(streamablehttp_client(url))
        sess = await exit_stack.enter_async_context(ClientSession(read, write))
    else:
        raise RuntimeError(f"Unknown mode: {spec.get('mode')}")
    await sess.initialize()
    session = sess
    return session

async def close_session():
    global session
    try:
        await exit_stack.aclose()
    finally:
        session = None

async def main():
    try:
        for s in steps:
            sess = await ensure_session()
            result = await sess.call_tool(s['tool'], s.get('args') or {})
            payload = getattr(result, 'content', None) or getattr(result, 'result', None)
            print('tool', s['tool'], '->', json.dumps(to_jsonable(payload), ensure_ascii=False))
            if not bool(s.get('keep_session_open', False)):
                await close_session()
    finally:
        await close_session()

if __name__ == '__main__':
    asyncio.run(main())
